"""Bundles ``design/`` into ``static/build/``.

Three stylesheets and one script become one of each, fingerprinted by content
so they can be served immutable. In development the bundle rebuilds whenever a
source file's mtime moves; in production it is built once, at deploy time.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import re
from pathlib import Path

#: Concatenation order matters: fonts declares the @font-face rules the rest
#: of the sheet names, and tokens defines the custom properties that base and
#: components consume. fonts.css is generated by scripts/fetch_fonts.py.
CSS_SOURCES = ("fonts.css", "tokens.css", "base.css", "components.css")
JS_SOURCES = ("app.js",)

#: A second, deliberately separate bundle: GSAP, ScrollTrigger and the motion
#: module that drives them.
#:
#: It is not folded into the first one because the first one runs the hero.
#: 116 KB of vendor code parsed ahead of app.js would push the cycle's start
#: past the second it is budgeted, to decorate sections nobody has scrolled to
#: yet. Two deferred scripts cost one extra request and buy the hero its
#: start time back.
#:
#: Vendor files are served from static/js/vendor/ and read from there rather
#: than design/, because they are not ours to edit.
MOTION_VENDOR = ("gsap.min.js", "ScrollTrigger.min.js")
MOTION_SOURCES = ("motion.js",)

MANIFEST = "manifest.json"


def _squeeze_css(text: str) -> str:
    """Strip comments and collapse whitespace.

    Deliberately conservative — no selector merging, no colour rewriting. The
    stylesheet is ~30 KB and gzip does the real work; the goal here is to drop
    the commentary, which is more than half the file.
    """
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s*([{}:;,>])\s*", r"\1", text)
    text = re.sub(r";}", "}", text)
    return text.strip()


def _squeeze_js(text: str) -> str:
    """Drop full-line comments and blank lines.

    Not a minifier. Rewriting JavaScript with regular expressions breaks on
    the first regex literal or template string that looks like a comment, and
    a 6 KB script does not justify pulling in a real one.
    """
    out = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        out.append(stripped)
    return "\n".join(out)


def _digest(payload: str) -> str:
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:10]


def _write(path: Path, payload: str) -> None:
    path.write_text(payload, encoding="utf-8")
    # nginx has gzip_static but not brotli on this host, so ship a .gz
    # alongside and let the edge handle Brotli.
    with gzip.open(path.with_suffix(path.suffix + ".gz"), "wt",
                   encoding="utf-8", compresslevel=9) as fh:
        fh.write(payload)


def build(design_dir: Path, build_dir: Path) -> dict[str, str]:
    """Build the bundle and return the manifest."""
    build_dir.mkdir(parents=True, exist_ok=True)

    css = _squeeze_css("\n".join(
        (design_dir / name).read_text(encoding="utf-8") for name in CSS_SOURCES
    ))
    js = _squeeze_js("\n".join(
        (design_dir / name).read_text(encoding="utf-8") for name in JS_SOURCES
    ))

    # Vendor code is already minified and is not ours to squeeze — running the
    # regex minifier over it would be a lot of risk for no bytes.
    vendor_dir = design_dir.parent / "static" / "js" / "vendor"
    motion = "\n".join(
        [(vendor_dir / name).read_text(encoding="utf-8") for name in MOTION_VENDOR]
        + [_squeeze_js((design_dir / name).read_text(encoding="utf-8"))
           for name in MOTION_SOURCES]
    )

    manifest = {
        "css": f"kmq.{_digest(css)}.css",
        "js": f"kmq.{_digest(js)}.js",
        "motion": f"kmq-motion.{_digest(motion)}.js",
    }

    # Clear superseded fingerprints so the directory does not grow forever.
    keep = set(manifest.values()) | {MANIFEST}
    for stale in build_dir.iterdir():
        if stale.name.removesuffix(".gz") not in keep:
            stale.unlink()

    _write(build_dir / manifest["css"], css)
    _write(build_dir / manifest["js"], js)
    _write(build_dir / manifest["motion"], motion)
    (build_dir / MANIFEST).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def newest_mtime(design_dir: Path) -> float:
    vendor_dir = design_dir.parent / "static" / "js" / "vendor"
    return max(
        [(design_dir / name).stat().st_mtime
         for name in CSS_SOURCES + JS_SOURCES + MOTION_SOURCES]
        + [(vendor_dir / name).stat().st_mtime for name in MOTION_VENDOR]
    )


def load_manifest(build_dir: Path) -> dict[str, str] | None:
    path = build_dir / MANIFEST
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
