#!/usr/bin/env python3
"""Pull the four families off Google Fonts once, so the browser never has to.

The site used to load a render-blocking <link> to fonts.googleapis.com, which
costs a DNS lookup, a TLS handshake and a round trip before the first glyph is
even requested — on the Arabic page, where the faces are large, that was a
visible slice of LCP.

This fetches the woff2 files, keeps only the unicode ranges each family is
actually for, and writes design/fonts.css against local paths. Run it when a
weight is added or dropped; the output is committed, so a build does not need
the network.

    python3 scripts/fetch_fonts.py

Only the subsets named in FAMILIES are kept. Google splits every family into
per-range files, so asking for "arabic" on Tajawal skips the Latin cut it also
ships — about a third of the bytes, for glyphs the Arabic page never draws.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "static" / "fonts"
CSS_OUT = ROOT / "design" / "fonts.css"

#: Chrome's UA, because the css2 endpoint serves woff2 only to browsers that
#: it believes support woff2. With urllib's default UA it returns ttf.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/124.0.0.0 Safari/537.36")

#: family -> (weights, subsets to keep)
#: Latin display and body; Arabic display and body. Space Grotesk carries the
#: eyebrows and numerals in *both* locales, so it keeps a middle weight the
#: other Latin face does not need.
FAMILIES = {
    "Space Grotesk": ([500, 600, 700], {"latin"}),
    "Inter":         ([400, 600],      {"latin"}),
    "Tajawal":       ([700, 800],      {"arabic"}),
    "Almarai":       ([400, 700],      {"arabic"}),
}

#: The two faces each locale hits first and hardest. base.html preloads these
#: and nothing else — preloading more competes with the hero image.
PRELOAD = {"Almarai-400", "Tajawal-700", "Inter-400", "SpaceGrotesk-700"}

BLOCK = re.compile(
    r"/\*\s*(?P<subset>[\w\[\]-]+)\s*\*/\s*"
    r"@font-face\s*\{(?P<body>[^}]*)\}", re.S)


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def field(body: str, name: str) -> str:
    m = re.search(rf"{name}:\s*([^;]+);", body)
    return m.group(1).strip() if m else ""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rules: list[str] = []
    kept = dropped = 0

    for family, (weights, subsets) in FAMILIES.items():
        spec = f"{family.replace(' ', '+')}:wght@{';'.join(str(w) for w in weights)}"
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()

        for m in BLOCK.finditer(css):
            subset, body = m.group("subset"), m.group("body")
            if subset not in subsets:
                dropped += 1
                continue

            weight = field(body, "font-weight")
            url = re.search(r"url\((https://[^)]+\.woff2)\)", body)
            if not url:
                sys.exit(f"{family} {weight}: no woff2 in the block Google returned")

            stem = f"{family.replace(' ', '')}-{weight}"
            path = OUT_DIR / f"{stem}.woff2"
            path.write_bytes(get(url.group(1)))
            kept += 1
            print(f"  {path.relative_to(ROOT)}  {path.stat().st_size / 1024:.1f} KB")

            rules.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight};\n"
                "  font-display: swap;\n"
                # Relative to the *bundle*, static/build/kmq.<hash>.css — the
                # design/ sources are concatenated, never served themselves.
                f"  src: url('../fonts/{stem}.woff2') format('woff2');\n"
                f"  unicode-range: {field(body, 'unicode-range')};\n"
                "}"
            )

    CSS_OUT.write_text(
        "/* Generated by scripts/fetch_fonts.py — do not hand-edit.\n"
        "   Self-hosted so no request leaves the origin before the first glyph\n"
        "   paints. Ranges are Google's own; the families are subset to the one\n"
        "   script each is drawn for. */\n\n"
        + "\n\n".join(rules) + "\n"
    )
    print(f"\n{CSS_OUT.relative_to(ROOT)}  ({kept} faces kept, {dropped} other subsets dropped)")
    print("preload in base.html:", ", ".join(sorted(PRELOAD)))


if __name__ == "__main__":
    main()
